apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: smh-postgres:5432
    user: smh_user
    secureJsonData:
      password: smh_pass
    jsonData:
      database: smh_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true