FROM apache/spark:3.5.0

USER root

# Install pip
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade pip

# Copy requirements
COPY /spark/requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# PostgreSQL JDBC driver
ADD https://jdbc.postgresql.org/download/postgresql-42.7.3.jar /opt/spark/jars/

# Working directory
WORKDIR /app

# Copy all files to container
COPY . .

ENV PYTHONPATH=/app/spark

USER 185