x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile.airflow
  env_file:
    - ../.env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    DATA_PATH: /opt/airflow/data/raw
    POSTGRES_JAR_PATH: /opt/airflow/jars/postgresql-42.7.3.jar
    PYTHONPATH: /opt/airflow/spark 
  volumes:
    - ../dags:/opt/airflow/dags
    - ../logs:/opt/airflow/logs
    - ../plugins:/opt/airflow/plugins
    - ../spark:/opt/airflow/spark
    - ../data:/opt/airflow/data
  depends_on:
    airflow-postgres:
      condition: service_healthy
  networks:
    - smh-network

services:

  # Pipeline Database
  postgres:
    image: postgres:14
    container_name: smh-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - smh-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # Spark
  spark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    container_name: smh-spark
    env_file:
      - ../.env
    environment:
      - SPARK_MODE=master
    volumes:
      - ../:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - smh-network

  # Airflow Metadata Database
  airflow-postgres:
    image: postgres:14
    container_name: airflow-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data
    networks:
      - smh-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_POSTGRES_USER}"]
      interval: 5s
      retries: 5

  # Airflow Init (One-time setup)
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
        --username ${AIRFLOW_ADMIN_USERNAME} \
        --password ${AIRFLOW_ADMIN_PASSWORD} \
        --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
        --lastname ${AIRFLOW_ADMIN_LASTNAME} \
        --role Admin \
        --email ${AIRFLOW_ADMIN_EMAIL} &&
        airflow connections add 'smh-postgres' \
        --conn-type postgres \
        --conn-host ${POSTGRES_HOST} \
        --conn-port ${POSTGRES_PORT} \
        --conn-schema ${POSTGRES_DB} \
        --conn-login ${POSTGRES_USER} \
        --conn-password ${POSTGRES_PASSWORD}
    restart: on-failure

  # Airflow Scheduler
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  # Airflow Webserver
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 5

networks:
  smh-network:
    driver: bridge

volumes:
  pg_data:
  airflow_pg_data: