# x-airflow-common is a reusable configuration for Airflow services (init, scheduler, webserver)
# not in services section because it's not a standalone service, but a template for other services
x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile.airflow
  env_file:
    - ../.env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    DATA_PATH: /opt/airflow/data/raw
    POSTGRES_JAR_PATH: /opt/airflow/jars/postgresql-42.7.3.jar
    PYTHONPATH: /opt/airflow/spark 
  volumes:
    - ../dags:/opt/airflow/dags
    - ../logs:/opt/airflow/logs
    - ../plugins:/opt/airflow/plugins
    - ../spark:/opt/airflow/spark
    - ../data:/opt/airflow/data
  depends_on:
    airflow-postgres:
      condition: service_healthy
  networks:
    - smh-network

services:

  # Pipeline Database for storing processed data (separate from Airflow's metadata database)
  postgres:
    image: postgres:14
    container_name: smh-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - smh-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  # Spark for data processing
  spark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.spark
    container_name: smh-spark
    env_file:
      - ../.env
    environment:
      - SPARK_MODE=master
    volumes:
      - ../:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - smh-network

  # Airflow Metadata Database for Airflow's internal use (separate from pipeline database)
  airflow-postgres:
    image: postgres:14
    container_name: airflow-postgres
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - airflow_pg_data:/var/lib/postgresql/data
    networks:
      - smh-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_POSTGRES_USER}"]
      interval: 5s
      retries: 5

  # Airflow Init (One-time setup) for initializing the database and creating admin user
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
        --username ${AIRFLOW_ADMIN_USERNAME} \
        --password ${AIRFLOW_ADMIN_PASSWORD} \
        --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
        --lastname ${AIRFLOW_ADMIN_LASTNAME} \
        --role Admin \
        --email ${AIRFLOW_ADMIN_EMAIL} &&
        airflow connections add 'smh-postgres' \
        --conn-type postgres \
        --conn-host ${POSTGRES_HOST} \
        --conn-port ${POSTGRES_PORT} \
        --conn-schema ${POSTGRES_DB} \
        --conn-login ${POSTGRES_USER} \
        --conn-password ${POSTGRES_PASSWORD}
    restart: on-failure

  # Airflow Scheduler for orchestrating tasks
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  # Airflow Webserver for UI access
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 5
  
  # Producer (Python)
  #   ↓ send JSON messages
  # Kafka Broker (Docker)
  #   ↓ 2 topics: olist.orders & olist.payments
  # Spark Structured Streaming (Consumer)
  #   ↓ read streaming data from Kafka topics, transform it, and write to PostgreSQL
  # PostgreSQL streaming schema
  #   → streaming.orders
  #   → streaming.payments

  # Zookeeper for Kafka coordination
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - smh-network

  # Kafka Broker for messaging
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - smh-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      retries: 5

  # Kafka Producer
  kafka-producer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.producer
    container_name: kafka-producer
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PRODUCER_INTERVAL_SECONDS: 2
    networks:
      - smh-network
  
  kafka-consumer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.consumer
    container_name: kafka-consumer
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - smh-network
    restart: on-failure

networks:
  smh-network:
    driver: bridge

volumes:
  pg_data:
  airflow_pg_data: